# Generated by Django 4.2.4 on 2023-08-30 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameMaster_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamemaster',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AddField(
            model_name='gamemaster',
            name='nickname',
            field=models.CharField(default='', max_length=64),
        ),
    ]
