# Generated by Django 4.2.4 on 2023-08-30 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GameMaster_app', '0004_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamemaster',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='player',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='gamemaster',
            name='nickname',
            field=models.OneToOneField(limit_choices_to={'is_game_master': True}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='GameMaster_app.user'),
        ),
        migrations.AlterField(
            model_name='player',
            name='nickname',
            field=models.OneToOneField(limit_choices_to={'is_player': True}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='GameMaster_app.user'),
        ),
    ]
