# Generated by Django 4.2.4 on 2023-09-01 16:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('GameMaster_app', '0006_gamemaster_is_game_master_player_is_player_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamemaster',
            options={'ordering': ['-creation_date']},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['-creation_date']},
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(choices=[('Rpg1', 'Fajny system'), ('Rpg2', 'Dobry system'), ('Rpg3', 'Taki sobie system'), ('NN', 'Inny system')], default='NN', max_length=4)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=256)),
                ('slots', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('session_date', models.DateTimeField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GameMaster_app.gamemaster')),
            ],
            options={
                'ordering': ['-creation_date'],
            },
        ),
    ]
