# Generated by Django 4.2.4 on 2023-09-01 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GameMaster_app', '0009_charactersheet_alter_playercharacter_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='charactersheet',
            options={'ordering': ['-creation_date', 'character_id']},
        ),
        migrations.AlterModelOptions(
            name='gamemaster',
            options={'ordering': ['-creation_date', 'nickname']},
        ),
        migrations.AlterModelOptions(
            name='gamesession',
            options={'ordering': ['-creation_date', 'owner_id', 'session_date']},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['-creation_date', 'user_id']},
        ),
        migrations.AlterModelOptions(
            name='playercharacter',
            options={'ordering': ['-creation_date', 'owner_id', 'game_session_id']},
        ),
    ]
