# Generated by Django 4.2.4 on 2023-09-08 15:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('GameMaster_app', '0010_alter_charactersheet_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='charactersheet',
            options={'ordering': ['-character_id']},
        ),
        migrations.RemoveField(
            model_name='charactersheet',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='charactersheet',
            name='name',
        ),
        migrations.RemoveField(
            model_name='gamesession',
            name='system',
        ),
        migrations.CreateModel(
            name='GameSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(choices=[('Rpg1', 'Fajny system'), ('Rpg2', 'Dobry system'), ('Rpg3', 'Taki sobie system'), ('NN', 'Inny system')], default='NN', max_length=4)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GameMaster_app.gamesession')),
            ],
            options={
                'ordering': ['-creation_date', 'session_id'],
            },
        ),
    ]
