# Generated by Django 4.2.4 on 2023-09-08 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GameMaster_app', '0012_alter_playercharacter_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamemaster',
            options={'ordering': ['-creation_date', 'user_id']},
        ),
        migrations.RenameField(
            model_name='gamemaster',
            old_name='nickname',
            new_name='user_id',
        ),
    ]
